name: vibe_games
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^1.0.3
  intl: ^0.18.1
  get: ^4.6.3
  vfx_flutter_common:
    git:
      url: https://gitlab.com/frostyland/vfx_flutter_common.git
      ref: "torexo"



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/fonts/

  
  fonts:
  - family: TTNorms
    fonts:
      - asset: assets/fonts/TTNorms/TTNorms-Light.ttf
        weight: 100
      - asset: assets/fonts/TTNorms/TTNorms-Regular.ttf
        style: normal
      - asset: assets/fonts/TTNorms/TTNorms-Medium.ttf
        weight: 200
      - asset: assets/fonts/TTNorms/TTNorms-Bold.ttf
        weight: 300
      - asset: assets/fonts/TTNorms/TTNorms-ExtraBold.ttf
        weight: 400       
      - asset: assets/fonts/TTNorms/TTNorms-Black.ttf
        weight: 500           

